# Generated by Django 2.2 on 2021-04-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_register_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
